owner: cattomgithub
repo: monitor

sites:
  - name: 2 Ucloud Beijing
    check: "tcp-ping"
    url: $SECRET_URL_1
    port: 22
  - name: 3 Buyvm Las Vegas
    check: "tcp-ping"
    url: $SECRET_URL_2
    port: 22
  - name: Blog
    url: https://blog.cattom.site
  - name: Note
    url: https://note.cattom.site
  - name: Cloud
    url: https://cloud.cattom.site:81
  - name: Drive
    url: https://drive.cattom.site
  - name: AriaNg
    url: https://ariang.cattom.site
  - name: SSL Certs Check
    url: https://cert.cattom.site
  - name: Get acme
    url: https://get.acme.cattom.site

assignees:
  - cattomgithub

status-website:
  cname: status.cattom.site
  # baseUrl: /monitor
  favicon: https://static.cattom.site/image/icon/favicon.ico
  logoUrl: https://static.cattom.site/image/icon/192.png
  name: Cat Tom Service Uptime
  introTitle: "**Cat Tom Service Uptime**"
  introMessage: To be, or not to be, that is the question.
  navbar:
    - title: Blog
      href: https://blog.cattom.site
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
